name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Build the Docker image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: build.sh
